################################################################################################
#
# Shotgun Pipeline Toolkit Default VFX Configuration
#

description: Apps and Engines showing when an engine is launched with a project only context.

#################################################################################################
# include common definitions for all the launchers that are used to start maya, nuke etc.

include: ./includes/app_launchers.yml


#################################################################################################
# define all the items that should appear in this environment 

engines:
  
  tk-3dsmax:
    apps:
      tk-multi-about:
        location: {name: tk-multi-about, type: app_store, version: v0.1.10}
      tk-multi-workfiles:
        hook_copy_file: default
        hook_scene_operation: default
        location: {name: tk-multi-workfiles, type: app_store, version: v0.3.3}
        sg_entity_types: [Shot, Asset]
        template_publish: null
        template_publish_area: null
        template_work: null
        template_work_area: null
    debug_logging: false
    location: {name: tk-3dsmax, type: app_store, version: v0.2.8}
  
  tk-hiero:
    apps:
      tk-hiero-openinshotgun:
        location: {name: tk-hiero-openinshotgun, type: app_store, version: v0.1.0}
        
      tk-hiero-export:
        location: {name: tk-hiero-export, type: app_store, version: v0.1.1}
        hook_translate_template: default        
        template_plate_path: hiero_plate_path
        template_nuke_script_path: hiero_nuke_script_path
        template_render_path: hiero_render_path
        default_task_template: Basic shot template
        
      tk-multi-about:
        location: {name: tk-multi-about, type: app_store, version: v0.1.10}
      
      tk-multi-publish:
        display_name: Publish Project
        hook_copy_file: default
        hook_post_publish: default
        hook_primary_pre_publish: default
        hook_primary_publish: default
        hook_scan_scene: default
        hook_secondary_pre_publish: default
        hook_secondary_publish: default
        hook_thumbnail: default
        location: {name: tk-multi-publish, type: app_store, version: v0.3.0}
        primary_description: Publish and version up the selected Hiero project
        primary_display_name: Hiero Publish
        primary_icon: icons/publish_hiero_main.png
        primary_publish_template: hiero_project_publish
        primary_scene_item_type: work_file
        primary_tank_type: Hiero Project
        secondary_outputs: []
        template_work: hiero_project_work
      
      tk-multi-snapshot:
        hook_copy_file: default
        hook_scene_operation: default
        hook_thumbnail: default
        location: {name: tk-multi-snapshot, type: app_store, version: v0.2.0}
        template_snapshot: hiero_project_snapshot
        template_work: hiero_project_work
      
      tk-multi-workfiles:
        hook_copy_file: default
        hook_scene_operation: default
        location: {name: tk-multi-workfiles, type: app_store, version: v0.3.3}
        sg_entity_types: []
        template_publish: hiero_project_publish
        template_publish_area: hiero_project_publish_area
        template_work: hiero_project_work
        template_work_area: hiero_project_work_area
    
    bin_context_menu:
    - {app_instance: tk-multi-workfiles, keep_in_menu: false, name: Shotgun Save As...,
      requires_selection: true}
    - {app_instance: tk-multi-workfiles, keep_in_menu: false, name: Version up Current
        Scene..., requires_selection: true}
    - {app_instance: tk-multi-snapshot, keep_in_menu: false, name: Snapshot..., requires_selection: true}
    - {app_instance: tk-multi-snapshot, keep_in_menu: false, name: Snapshot History...,
      requires_selection: true}
    - {app_instance: tk-multi-publish, keep_in_menu: false, name: Publish Project...,
      requires_selection: true}
    debug_logging: false
    location: {name: tk-hiero, type: app_store, version: v0.2.1}
    menu_favourites:
    - {app_instance: tk-multi-workfiles, name: Shotgun File Manager...}
    spreadsheet_context_menu:
    - {app_instance: tk-hiero-openinshotgun, keep_in_menu: false, name: Open in Shotgun,
      requires_selection: true}
    timeline_context_menu:
    - {app_instance: tk-hiero-openinshotgun, keep_in_menu: false, name: Open in Shotgun,
      requires_selection: true}
  tk-maya:
    apps:
      tk-multi-about:
        location: {name: tk-multi-about, type: app_store, version: v0.1.10}
      tk-multi-workfiles:
        hook_copy_file: default
        hook_scene_operation: default
        location: {name: tk-multi-workfiles, type: app_store, version: v0.3.3}
        sg_entity_types: [Shot, Asset]
        template_publish: null
        template_publish_area: null
        template_work: null
        template_work_area: null
    debug_logging: false
    location: {name: tk-maya, type: app_store, version: v0.3.4}
    menu_favourites:
    - {app_instance: tk-multi-workfiles, name: Shotgun File Manager...}
    template_project: null
    use_sgtk_as_menu_name: false
  tk-nuke:
    apps:
      tk-multi-about:
        location: {name: tk-multi-about, type: app_store, version: v0.1.10}
      tk-multi-workfiles:
        hook_copy_file: default
        hook_scene_operation: default
        location: {name: tk-multi-workfiles, type: app_store, version: v0.3.3}
        sg_entity_types: [Shot, Asset]
        template_publish: null
        template_publish_area: null
        template_work: null
        template_work_area: null
    debug_logging: false
    location: {name: tk-nuke, type: app_store, version: v0.2.12}
    menu_favourites:
    - {app_instance: tk-multi-workfiles, name: Shotgun File Manager...}
    use_sgtk_as_menu_name: false
  tk-houdini:
    apps:
      tk-multi-about:
        location: {name: tk-multi-about, type: app_store, version: v0.1.10}
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-workfiles:
        hook_copy_file: default
        hook_scene_operation: default
        location: {name: tk-multi-workfiles, type: app_store, version: v0.3.3}
        sg_entity_types: [Shot, Asset]
        template_publish: null
        template_publish_area: null
        template_work: null
        template_work_area: null
    debug_logging: false
    location: {name: tk-houdini, type: app_store, version: v0.1.4}
    menu_favourites:
    - {app_instance: tk-multi-workfiles, name: Shotgun File Manager...}


  tk-shell:
    apps: 
      tk-multi-launch3dsmax: '@launch_3dsmax'
      tk-multi-launchmaya: '@launch_maya'
      tk-multi-launchnuke: '@launch_nuke'
      tk-multi-launchhiero: '@launch_hiero'
    debug_logging: false
    location: {name: tk-shell, type: app_store, version: v0.3.1}


frameworks:
  tk-framework-widget_v0.1.1:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.1}
  tk-framework-widget_v0.1.10:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.10}
  tk-framework-widget_v0.1.12:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.12}
  tk-framework-widget_v0.1.13:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.13}
  tk-framework-widget_v0.1.15:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.15}
  tk-framework-widget_v0.1.3:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.3}
  tk-framework-widget_v0.1.4:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.4}
  tk-framework-widget_v0.1.5:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.5}

